### ISSUE TITLE
Create Testing Database

### ISSUE THREAD

**Issue by mchlp** [waterloop/teamhub#10]

**Comment by mrkarezina** [comment]
Create a script for changing config.js file for local Mongo connection, when tests are running on Circle CI

**Comment by mrkarezina** [comment]
Now that docker is set up, can use local mongo instance for all development. We can add a `config.test.json` in `/backend`, and specify `NODE_ENV=development` as part of `npm run dev`. Then use the local DB if in dev mode.

**Comment by mchlp** [comment]
@mrkarezina Should we continue using the docker mongo connection on local and Circle CI testing?

**Comment by mchlp** [comment]
Local mongo DB on docker added in ee1b000c634d929261d4cf57e6885c69d340d142

**Comment by mrkarezina** [comment]
> @mrkarezina Should we continue using the docker mongo connection on local and Circle CI testing?

What alternative were you thinking of?

**Comment by mchlp** [comment]
@mrkarezina If it works now then I think we should keep it as it is. But if it doesn't work we can come up with an alternative.

**Comment by mchlp** [comment]
Completed by 10598263f080128864083c4ff8dbfbfc3c432b3f
