### ISSUE TITLE
Deploy to AWS

### ISSUE THREAD

**Issue by mrkarezina** [waterloop/teamhub#39]

**Comment by mchlp** [comment]
https://circleci.com/docs/2.0/configuration-cookbook/#header3

**Comment by mrkarezina** [comment]
Continuous deploy to Ziet now: https://medium.com/@niccai/getting-zeits-now-working-with-circleci-1bed77d80f27

**Comment by mrkarezina** [comment]
Add a config.production.json for remote production mongodb

**Comment by mrkarezina** [comment]
Move backend code to `page/api` so deployment on Zeit Now works.
